# -*- coding: utf-8 -*-
"""Python 25-01-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJz4iDBHNyEk75wy2sJfoQfQKH_P1lI7

Khushi Bagaria | E067 | BTech CSBS

# Python Basics 2 - 25/01/2025

---


Reverse of 3 digit number without using shortcut/loop
"""

num = int(input("Enter number: "))

n1 = num%10
num = num//10
n2 = num%10
num = num//10
n3 = num%10

rev = n1*100 +  n2*10 + n3*1

print("Reverse of a 3 digit number is:", rev)

"""---
Find the sum of first and last digit of a 9 digit number in 3 steps
"""

num = int(input("Enter number: "))

n1 = num%10
n2 = (num//100000000)%10
res = n1 + n2

print("Sum of first and last digit is:", res)

"""---
Addition of 2 numbers without using variables
"""

print("Sum is:",(int(input("First no.: "))+int(input("Second no.: "))))

"""---
eval() function
"""

a = eval(input("Enter equation: "))
print(a)

"""Note: [ ] list,
( ) tuple,
{ } set,
{key, value} dictionary

using this we can accept diffierent data types
"""

a = eval(input("Enter data: "))
print(a)
print(type(a))

"""---
Output statement

sep attribute
"""

a, b, c = 10, 20, 30
print(a, b, c)
print(a, b, c, sep='')
print(a, b, c, sep=' ')
print(a, b, c, sep=',')
print(a, b, c, sep=':')

"""end attribute"""

print("Khushi")
print("Bagaria")
print("Khushi", end=' ')
print("Bagaria")
print("Khushi", end='')
print("Bagaria")

"""replacement operator"""

name = 'Khushi'
salary = 1600000
company = 'Google'
print("Hello {0} your salary is {1} and Company is {2}".format(name,salary,company))
print("Hello {x} your salary is {y} and Company is {z}".format(x = name, z = company, y = salary))

"""---
Control Flow

Accept 5 numbers and find max number using if only
"""

n1 = int(input("Enter numbers: "))
n2 = int(input())
n3 = int(input())
n4 = int(input())
n5 = int(input())

max = n1
if n2>max: max=n2
if n3>max: max=n3
if n4>max: max=n4
if n5>max: max=n5

print("Max is:",max)

"""uppercase, lowercase, lowercase, digit, symbol"""

ch = input("Enter character: ")
c = ord(ch)
if c>=65 and c<=90:
  print("Uppercase")
elif c>=97 and c<=122:
  print("Lowercase")
elif c>=48 and c<=57:
  print("Digit")
else:
  print("Special Symbol")

"""---
Loops

note: before answering "What is requirement of loop" talk about why its is required (print name 1000 times)

definition: if you want to execute a block of statements repeatedly till the condition is satisfied, use loops

**difference between for loop and while loop:** for loop is used when range is given, while loop is used when range is not given

Reverse of a number using while loop:
"""

n = int(input("Enter number: "))
rev = 0
while n>0:
  rem = n%10
  rev = rev*10 + rem
  n = n//10
print("Reverse is:", rev)

"""Sum of digits using loop"""

n = int(input("Enter number: "))
sum = 0
while n>0:
  rem = n%10
  sum = sum + rem
  n = n//10
print("Sum is:", sum)

"""Count number of digits"""

n = int(input("Enter number: "))
digit = 0
while n>0:
  rem = n%10
  digit = digit + 1
  n = n//10
print("No. of digits is:", digit)

"""Armstrong Number"""

n = int(input("Enter number: "))
num, final = n, n
sum = 0

digit = 0
while n>0:
  rem = n%10
  digit = digit + 1
  n = n//10

while num>0:
  rem = num%10
  sum = sum + rem**digit
  num = num//10

if sum == final:
  print("Armstrong Number")
else:
  print("Not Armstrong Number")

"""Peterson Number"""

n = int(input("Enter number: "))
num = n
sum = 0

while num>0:
  rem = num%10
  fact = 1
  for i in range(1,rem+1): # +1 as the number itself is also included in factorial
    fact = fact*i
  num = num//10
  sum = sum + fact

if sum==n:
  print("Peterson Number")
else:
  print("Not Peterson Number")

"""Tech Number"""

n = int(input("Enter number: "))
num, final = n, n
sum = 0

digit = 0
while n>0:
  rem = n%10
  digit = digit + 1
  n = n//10

n1 = num%10**digit//2
n2 = num//10**digit//2
sum = n1 + n2
prod = sum**2

if prod==final:
  print("Tech Number")
else:
  print("Not Tech Number")

"""Homework:

Write a Python program that takes an amount in Indian Rupees (Rs) as input from the user and then calculates and prints the minimum number of notes and coins of different denominations (Rs 500, Rs 200, Rs 100, Rs 50, Rs 20, Rs 10, Rs 5, Rs 2, Rs 1) required to represent that amount.
"""

n = int(input("Enter Amount (in Rs): "))

if n>500:
  n_500 = n//500
  n = n%500
  print("Number of Rs 500 notes:", n_500)
if n>200:
  n_200 = n//200
  n = n%200
  print("Number of Rs 200 notes:", n_200)
if n>100:
  n_100 = n//100
  n = n%100
  print("Number of Rs 100 notes:", n_100)
if n>50:
  n_50 = n//50
  n = n%50
  print("Number of Rs 50 notes:", n_50)
if n>20:
  n_20 = n//20
  n = n%20
  print("Number of Rs 20 notes:", n_20)
if n>10:
  n_10 = n//10
  n = n%10
  print("Number of Rs 10 notes:", n_10)
if n>5:
  n_5 = n//5
  n = n%5
  print("Number of Rs 5 coins:", n_5)
if n>2:
  n_2 = n//2
  n = n%2
  print("Number of Rs 2 coins:", n_2)
if n>1:
  n_1 = n//1
  n = n%1
  print("Number of Rs 1 coins:", n_1)